# Generated by Django 5.2.6 on 2025-09-25 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_category_description_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveBigIntegerField()),
                ('delivery_price', models.PositiveBigIntegerField(default=0)),
                ('discout', models.PositiveBigIntegerField(default=0)),
                ('final_price', models.PositiveBigIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_app.basket')),
            ],
        ),
    ]
