# Generated by Django 5.2.6 on 2025-09-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_basket_owner_remove_basket_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='discout',
            new_name='discount',
        ),
    ]
