# Generated by Django 5.2.6 on 2025-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_basket_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='destination_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
