# Generated by Django 5.2.6 on 2025-10-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_otp_user_otp_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
